#ifndef INC_TESTDATA_INFO_SEAMLESS_SECP384_H
#define INC_TESTDATA_INFO_SEAMLESS_SECP384_H


/****************************************
 *
 * Information on FULL_PFR_IMAGE_PCH_FILE
 *
 * Re-defined some macros from testdata_info_secp384.h
 ****************************************/
#undef PCH_SPI_REGION1_START_ADDR
#undef PCH_SPI_REGION1_END_ADDR
#undef PCH_SPI_REGION2_START_ADDR
#undef PCH_SPI_REGION2_END_ADDR
#undef PCH_SPI_REGION3_START_ADDR
#undef PCH_SPI_REGION3_END_ADDR
#undef PCH_SPI_REGION4_START_ADDR
#undef PCH_SPI_REGION4_END_ADDR
#undef PCH_SPI_REGION5_START_ADDR
#undef PCH_SPI_REGION5_END_ADDR
#undef PCH_SPI_REGION6_START_ADDR
#undef PCH_SPI_REGION6_END_ADDR
#undef PCH_SPI_REGION7_START_ADDR
#undef PCH_SPI_REGION7_END_ADDR
#undef PCH_SPI_REGION8_START_ADDR
#undef PCH_SPI_REGION8_END_ADDR
#undef PCH_SPI_REGION9_START_ADDR
#undef PCH_SPI_REGION9_END_ADDR
#undef PCH_SPI_REGION10_START_ADDR
#undef PCH_SPI_REGION10_END_ADDR
#undef PCH_SPI_REGION11_START_ADDR
#undef PCH_SPI_REGION11_END_ADDR
#undef PCH_SPI_REGION12_START_ADDR
#undef PCH_SPI_REGION12_END_ADDR
#undef PCH_SPI_REGION13_START_ADDR
#undef PCH_SPI_REGION13_END_ADDR

#undef PCH_NUM_SPI_REGIONS
#undef PCH_SPI_REGIONS_START_ADDR
#undef PCH_SPI_REGIONS_END_ADDR

#undef PCH_NUM_STATIC_SPI_REGIONS
#undef PCH_STATIC_SPI_REGIONS_START_ADDR
#undef PCH_STATIC_SPI_REGIONS_END_ADDR

#undef PCH_NUM_DYNAMIC_SPI_REGIONS
#undef PCH_DYNAMIC_SPI_REGIONS_START_ADDR
#undef PCH_DYNAMIC_SPI_REGIONS_END_ADDR

/*
 * PCH SPI region offsets from the PFM
 *
 * Static SPI regions are: region 1/2/6/8/11/13
 * Dynamic SPI regions are: region 3/7/9/10/12
 * PFR SPI regions are: region 4/5
 */
// SPI regions in PFM
#define PCH_SPI_REGION1_START_ADDR 0x0
#define PCH_SPI_REGION1_END_ADDR 0x1000

#define PCH_SPI_REGION2_START_ADDR 0x1000
#define PCH_SPI_REGION2_END_ADDR 0x3000

#define PCH_SPI_REGION3_START_ADDR 0x7c7000
#define PCH_SPI_REGION3_END_ADDR 0x7c8000

#define PCH_SPI_REGION4_START_ADDR 0x7f0000
#define PCH_SPI_REGION4_END_ADDR 0x1bf0000

#define PCH_SPI_REGION5_START_ADDR 0x1bf0000
#define PCH_SPI_REGION5_END_ADDR 0x3000000

// ME FV REGION
#define PCH_SPI_REGION6_START_ADDR 0x3000
#define PCH_SPI_REGION6_END_ADDR 0x28000

#define PCH_SPI_REGION7_START_ADDR 0x28000
#define PCH_SPI_REGION7_END_ADDR 0x94000

#define PCH_SPI_REGION8_START_ADDR 0x94000
#define PCH_SPI_REGION8_END_ADDR 0x7c7000

// UCode1 FV REGION
#define PCH_SPI_REGION9_START_ADDR 0x7c8000
#define PCH_SPI_REGION9_END_ADDR 0x7e0000

// UCode2 FV REGION
#define PCH_SPI_REGION10_START_ADDR 0x7e0000
#define PCH_SPI_REGION10_END_ADDR 0x7f0000

// BIOS FV REGION
#define PCH_SPI_REGION11_START_ADDR 0x3000000
#define PCH_SPI_REGION11_END_ADDR 0x3850000

#define PCH_SPI_REGION12_START_ADDR 0x3850000
#define PCH_SPI_REGION12_END_ADDR 0x3900000

#define PCH_SPI_REGION13_START_ADDR 0x3900000
#define PCH_SPI_REGION13_END_ADDR 0x4000000

#define PCH_NUM_BIOS_FV_REGIONS 3
#define PCH_SPI_BIOS_FV_REGIONS_START_ADDR {\
        PCH_SPI_REGION11_START_ADDR, PCH_SPI_REGION12_START_ADDR, PCH_SPI_REGION13_START_ADDR\
}
#define PCH_SPI_BIOS_FV_REGIONS_END_ADDR {\
        PCH_SPI_REGION11_END_ADDR, PCH_SPI_REGION12_END_ADDR, PCH_SPI_REGION13_END_ADDR\
}

#define PCH_NUM_SPI_REGIONS 13
#define PCH_SPI_REGIONS_START_ADDR {\
        PCH_SPI_REGION1_START_ADDR, PCH_SPI_REGION2_START_ADDR, PCH_SPI_REGION3_START_ADDR,\
        PCH_SPI_REGION4_START_ADDR, PCH_SPI_REGION5_START_ADDR, PCH_SPI_REGION6_START_ADDR,\
        PCH_SPI_REGION7_START_ADDR, PCH_SPI_REGION8_START_ADDR, PCH_SPI_REGION9_START_ADDR,\
        PCH_SPI_REGION10_START_ADDR, PCH_SPI_REGION11_START_ADDR, PCH_SPI_REGION12_START_ADDR,\
        PCH_SPI_REGION13_START_ADDR\
}
#define PCH_SPI_REGIONS_END_ADDR {\
        PCH_SPI_REGION1_END_ADDR, PCH_SPI_REGION2_END_ADDR, PCH_SPI_REGION3_END_ADDR,\
        PCH_SPI_REGION4_END_ADDR, PCH_SPI_REGION5_END_ADDR, PCH_SPI_REGION6_END_ADDR,\
        PCH_SPI_REGION7_END_ADDR, PCH_SPI_REGION8_END_ADDR, PCH_SPI_REGION9_END_ADDR,\
        PCH_SPI_REGION10_END_ADDR, PCH_SPI_REGION11_END_ADDR, PCH_SPI_REGION12_END_ADDR,\
        PCH_SPI_REGION13_END_ADDR\
}

#define PCH_NUM_STATIC_SPI_REGIONS 6
#define PCH_STATIC_SPI_REGIONS_START_ADDR {\
        PCH_SPI_REGION1_START_ADDR, PCH_SPI_REGION2_START_ADDR, PCH_SPI_REGION6_START_ADDR,\
        PCH_SPI_REGION8_START_ADDR, PCH_SPI_REGION11_START_ADDR, PCH_SPI_REGION13_START_ADDR\
}
#define PCH_STATIC_SPI_REGIONS_END_ADDR {\
        PCH_SPI_REGION1_END_ADDR, PCH_SPI_REGION2_END_ADDR, PCH_SPI_REGION6_END_ADDR,\
        PCH_SPI_REGION8_END_ADDR, PCH_SPI_REGION11_END_ADDR, PCH_SPI_REGION13_END_ADDR\
}

#define PCH_NUM_DYNAMIC_SPI_REGIONS 5
#define PCH_DYNAMIC_SPI_REGIONS_START_ADDR {\
        PCH_SPI_REGION3_START_ADDR, PCH_SPI_REGION7_START_ADDR,\
        PCH_SPI_REGION9_START_ADDR, PCH_SPI_REGION10_START_ADDR, PCH_SPI_REGION12_START_ADDR\
}
#define PCH_DYNAMIC_SPI_REGIONS_END_ADDR {\
        PCH_SPI_REGION3_END_ADDR, PCH_SPI_REGION7_END_ADDR,\
        PCH_SPI_REGION9_END_ADDR, PCH_SPI_REGION10_END_ADDR, PCH_SPI_REGION12_END_ADDR\
}

#endif /* INC_TESTDATA_INFO_SEAMLESS_SECP384_H */
